// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.
#pragma once

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include <frc2/command/SubsystemBase.h>
#include <frc/drive/MecanumDrive.h>
#include <frc/motorcontrol/MotorControllerGroup.h>
#include <frc/motorcontrol/PWMSparkMax.h>

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include <AHRS.h>

/**
 *
 *
 * @author ExampleAuthor
 */
class DriveTrain: public frc2::SubsystemBase {
private:
    // It's desirable that everything possible is private except
    // for methods that implement subsystem capabilities
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
frc::MecanumDrive m_mecanumDrive{m_frontLeft, m_rearLeft, m_frontRight, m_rearRight};
frc::MotorControllerGroup m_rearRight{m_rearRight1, m_rearRight2  };
frc::PWMSparkMax m_rearRight1{7};
frc::PWMSparkMax m_rearRight2{6};
frc::MotorControllerGroup m_frontRight{m_frontRight1, m_frontRight2  };
frc::PWMSparkMax m_frontRight2{5};
frc::PWMSparkMax m_frontRight1{4};
frc::MotorControllerGroup m_rearLeft{m_rearLeft1, m_rearLeft2  };
frc::PWMSparkMax m_rearLeft2{3};
frc::PWMSparkMax m_rearLeft1{2};
frc::MotorControllerGroup m_frontLeft{m_frontLeft1, m_frontLeft2  };
frc::PWMSparkMax m_frontLeft2{1};
frc::PWMSparkMax m_frontLeft1{0};

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
DriveTrain();

    void Periodic() override;
    void SimulationPeriodic() override;
    void MechanumDrive(double mechX, double mechY, double mechRot);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS


};

