// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: RobotContainer.

#include "RobotContainer.h"
#include <frc2/command/ParallelRaceGroup.h>
#include <frc/smartdashboard/SmartDashboard.h>



RobotContainer* RobotContainer::m_robotContainer = NULL;

RobotContainer::RobotContainer(){
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
          

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SMARTDASHBOARD
    // Smartdashboard Subsystems
    frc::SmartDashboard::PutData(&m_ultrasonic);


    // SmartDashboard Buttons
    frc::SmartDashboard::PutData("ArmPos4", new ArmPos4( &m_pnenumatics ));
    frc::SmartDashboard::PutData("ArmPos3", new ArmPos3( &m_pnenumatics ));
    frc::SmartDashboard::PutData("ArmPos2", new ArmPos2( &m_pnenumatics ));
    frc::SmartDashboard::PutData("ArmPos1", new ArmPos1( &m_pnenumatics ));
    frc::SmartDashboard::PutData("CloseDisco", new CloseDisco( &m_pnenumatics ));
    frc::SmartDashboard::PutData("OpenDisco", new OpenDisco( &m_pnenumatics ));
    frc::SmartDashboard::PutData("AutoBalance", new AutoBalance( &m_driveTrain ));
    frc::SmartDashboard::PutData("AutoClose", new AutoClose( &m_pnenumatics ));
    frc::SmartDashboard::PutData("Teleop Drive", new TeleopDrive( &m_driveTrain ));
    frc::SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SMARTDASHBOARD

    ConfigureButtonBindings();

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT-COMMANDS
m_driveTrain.SetDefaultCommand(TeleopDrive( &m_driveTrain ));
m_driveTrain.SetDefaultCommand(TeleopDrive( &m_driveTrain ));

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT-COMMANDS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

    m_chooser.SetDefaultOption("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

    frc::SmartDashboard::PutData("Auto Mode", &m_chooser);

}

RobotContainer* RobotContainer::GetInstance() {
    if (m_robotContainer == NULL) {
        m_robotContainer = new RobotContainer();
    }
    return(m_robotContainer);
}

void RobotContainer::ConfigureButtonBindings() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

frc::XboxController* RobotContainer::getXboxController() {
   return &m_xboxController;
}
frc::Joystick* RobotContainer::getButtonBoard() {
   return &m_buttonBoard;
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS


frc2::Command* RobotContainer::GetAutonomousCommand() {
  // The selected command will be run in autonomous
  return m_chooser.GetSelected();
}
