// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: RobotContainer.

#include "RobotContainer.h"
#include <frc2/command/ParallelRaceGroup.h>
#include <frc/smartdashboard/SmartDashboard.h>



RobotContainer* RobotContainer::m_robotContainer = NULL;

RobotContainer::RobotContainer(){
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
          

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SMARTDASHBOARD
    // Smartdashboard Subsystems
    frc::SmartDashboard::PutData(&m_ultrasonic);


    // SmartDashboard Buttons
    frc::SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
    frc::SmartDashboard::PutData("Teleop Drive", new TeleopDrive( &m_driveTrain ));
    frc::SmartDashboard::PutData("AutoClaw", new AutoClaw( &m_pnenumatics ));
    frc::SmartDashboard::PutData("AutoBalance", new AutoBalance( &m_driveTrain ));
    frc::SmartDashboard::PutData("CloseDisco", new CloseDisco( &m_pnenumatics ));
    frc::SmartDashboard::PutData("OpenDisco", new OpenDisco( &m_pnenumatics ));
    frc::SmartDashboard::PutData("ArmPos1", new ArmPos1( &m_pnenumatics ));
    frc::SmartDashboard::PutData("ArmPos2", new ArmPos2( &m_pnenumatics ));
    frc::SmartDashboard::PutData("ArmPos3", new ArmPos3( &m_pnenumatics ));
    frc::SmartDashboard::PutData("ArmPos4", new ArmPos4( &m_pnenumatics ));

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SMARTDASHBOARD

    ConfigureButtonBindings();

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT-COMMANDS
m_driveTrain.SetDefaultCommand(TeleopDrive( &m_driveTrain ));
m_driveTrain.SetDefaultCommand(TeleopDrive( &m_driveTrain ));

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT-COMMANDS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

    m_chooser.SetDefaultOption("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

    frc::SmartDashboard::PutData("Auto Mode", &m_chooser);

}

RobotContainer* RobotContainer::GetInstance() {
    if (m_robotContainer == NULL) {
        m_robotContainer = new RobotContainer();
    }
    return(m_robotContainer);
}

void RobotContainer::ConfigureButtonBindings() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS

frc2::JoystickButton m_buttonArmPos1{&m_buttonBoard, 1};
frc2::JoystickButton m_buttonArmPos2{&m_buttonBoard, 2};
frc2::JoystickButton m_buttonArmPos3{&m_buttonBoard, 3};
frc2::JoystickButton m_buttonArmPos4{&m_buttonBoard, 4};
frc2::JoystickButton m_buttonOpenDisco{&m_buttonBoard, 5};
frc2::JoystickButton m_buttonCloseDisco{&m_buttonBoard, 6};
frc2::JoystickButton m_buttonAutoBalanceOn{&m_buttonBoard, 7};
frc2::JoystickButton m_buttonAutoBalanceOff{&m_buttonBoard, 8};
frc2::JoystickButton m_autoClawOn{&m_buttonBoard, 9};
frc2::JoystickButton m_autoClawOff{&m_buttonBoard, 1};

m_buttonArmPos1.OnTrue(ArmPos1( &m_pnenumatics ).WithInterruptBehavior(frc2::Command::InterruptionBehavior::kCancelSelf));

m_buttonArmPos2.OnTrue(ArmPos2( &m_pnenumatics ).WithInterruptBehavior(frc2::Command::InterruptionBehavior::kCancelSelf));

m_buttonArmPos3.OnTrue(ArmPos3( &m_pnenumatics ).WithInterruptBehavior(frc2::Command::InterruptionBehavior::kCancelSelf));

m_buttonArmPos4.OnTrue(ArmPos4( &m_pnenumatics ).WithInterruptBehavior(frc2::Command::InterruptionBehavior::kCancelSelf));

m_buttonOpenDisco.OnTrue(OpenDisco( &m_pnenumatics ).WithInterruptBehavior(frc2::Command::InterruptionBehavior::kCancelSelf));

m_buttonCloseDisco.OnTrue(CloseDisco( &m_pnenumatics ).WithInterruptBehavior(frc2::Command::InterruptionBehavior::kCancelSelf));

m_buttonAutoBalanceOn.OnTrue(AutoBalance( &m_driveTrain ).WithInterruptBehavior(frc2::Command::InterruptionBehavior::kCancelSelf));

m_buttonAutoBalanceOff.OnTrue(AutoBalance( &m_driveTrain ).WithInterruptBehavior(frc2::Command::InterruptionBehavior::kCancelSelf));

m_autoClawOn.OnTrue(AutoClaw( &m_pnenumatics ).WithInterruptBehavior(frc2::Command::InterruptionBehavior::kCancelSelf));

m_autoClawOff.OnTrue(AutoClaw( &m_pnenumatics ).WithInterruptBehavior(frc2::Command::InterruptionBehavior::kCancelSelf));


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

frc::Joystick* RobotContainer::getButtonBoard() {
   return &m_buttonBoard;
}
frc::XboxController* RobotContainer::getXboxController() {
   return &m_xboxController;
}

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS


frc2::Command* RobotContainer::GetAutonomousCommand() {
  // The selected command will be run in autonomous
  return m_chooser.GetSelected();
}